//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFolioBireysel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbDevFolioEntities : DbContext
    {
        public DbDevFolioEntities()
            : base("name=DbDevFolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblAdress> TblAdress { get; set; }
        public virtual DbSet<TblCategory> TblCategory { get; set; }
        public virtual DbSet<TblContact> TblContact { get; set; }
        public virtual DbSet<TblFeature> TblFeature { get; set; }
        public virtual DbSet<TblProfile> TblProfile { get; set; }
        public virtual DbSet<TblProject> TblProject { get; set; }
        public virtual DbSet<TblService> TblService { get; set; }
        public virtual DbSet<TblSkill> TblSkill { get; set; }
        public virtual DbSet<TblSocialMedia> TblSocialMedia { get; set; }
        public virtual DbSet<TblTestimonial> TblTestimonial { get; set; }
        public virtual DbSet<TblAbout> TblAbout { get; set; }
        public virtual DbSet<TblExperience> TblExperience { get; set; }
    
        public virtual ObjectResult<string> GetLastSkillTitle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetLastSkillTitle");
        }
    
        public virtual ObjectResult<string> GetFeatureHeaderTitle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetFeatureHeaderTitle");
        }
    
        public virtual ObjectResult<string> GetFeatureHeaderDescription()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetFeatureHeaderDescription");
        }
    
        public virtual ObjectResult<GetSocialMediaStatus1_Result> GetSocialMediaStatus1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSocialMediaStatus1_Result>("GetSocialMediaStatus1");
        }
    
        public virtual ObjectResult<getportfoliocategory_Result> getportfoliocategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getportfoliocategory_Result>("getportfoliocategory");
        }
    
        public virtual ObjectResult<string> GetUserPhoto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserPhoto");
        }
    
        public virtual ObjectResult<getLastTestimonial_Result> getLastTestimonial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLastTestimonial_Result>("getLastTestimonial");
        }
    
        public virtual ObjectResult<string> getLastTestimonial2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getLastTestimonial2");
        }
    
        public virtual ObjectResult<string> getLastTestimonialContect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getLastTestimonialContect");
        }
    }
}
